baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'Marco Morandin'

defaultContentLanguage = "en"  # Default language
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.it]
    languageName = "Italian"
    weight = 2

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'